

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PicturesAPI
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PicturesEntities : DbContext
{
    public PicturesEntities()
        : base("name=PicturesEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<CATEGORy> CATEGORIES { get; set; }

    public DbSet<User> Users { get; set; }

    public DbSet<SubCategory> SubCategories { get; set; }

    public DbSet<EmployeeInfo> EmployeeInfoes { get; set; }

    public DbSet<FavouriteItem> FavouriteItems { get; set; }

    public DbSet<ItemImage> ItemImages { get; set; }

    public DbSet<Item> Items { get; set; }

}

}

